### ISSUE TITLE
Builds lack src

### ISSUE THREAD

**Issue by marckrenn** [madmadi/instant-pixi-app-boilerplate#1]
Builds via `npm run build` won't copy `/src` over to `/dist`, resulting in missing assets.

**Comment by madmadi** [comment]
There is no need to copy src, assets will be copied using `require`/`import` statements.
https://github.com/madmadi/instant-pixi-app-boilerplate/blob/master/src/index.js#L11

**Comment by marckrenn** [comment]
In my infinite wisdom I immediately deleted the example. 

Got it now, thanks.
